image: node:latest

#  les étapes du pipeline
stages:
  - build
  - test
  - deploy

#  build du frontend (Angular)
build_frontend:
  stage: build
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --prod

# test du frontend (Angular)
test_frontend:
  stage: test
  script:
    - ng test

#  build du backend (Symfony)
build_backend:
  stage: build
  script:
    - cd back
    - composer install
    - php bin/console doctrine:migrations:migrate --no-interaction

# test du backend (Symfony)
test_backend:
  stage: test
  script:
    - cd back
    - php bin/console doctrine:fixtures:load --no-interaction
    - php vendor/bin/phpunit

#  déploiement
deploy:
  stage: deploy
  script:
    - echo " Deploy"
