stages:
  - build
  - test
  - deploy

variables:
  NG_CLI_VERSION: "16.0.0" # Version de Angular CLI à utiliser

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qy
  - apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_16.x | bash -
  - apt-get install -y nodejs
  - npm install -g @angular/cli@${NG_CLI_VERSION}
  - npm install
  - composer install --prefer-dist --no-interaction
  - cp .env.example .env
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --env=test --force

build:
  stage: build
  script:
    - ng build --prod

test:
  stage: test
  script:
    - ng test --watch=false --code-coverage

deploy_staging:
  stage: deploy
  script:
