<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxWaZJr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxWaZJr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxWaZJr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxWaZJr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWxWaZJr\App_KernelDevDebugContainer([
    'container.build_hash' => 'WxWaZJr',
    'container.build_id' => 'b71a5b4b',
    'container.build_time' => 1686235912,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxWaZJr');
