<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVDFjrOl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVDFjrOl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVDFjrOl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVDFjrOl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVDFjrOl\App_KernelDevDebugContainer([
    'container.build_hash' => 'VDFjrOl',
    'container.build_id' => '57eee2c3',
    'container.build_time' => 1686313239,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVDFjrOl');
