<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN2tiwSQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN2tiwSQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN2tiwSQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN2tiwSQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN2tiwSQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'N2tiwSQ',
    'container.build_id' => '35dbe746',
    'container.build_time' => 1690290983,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN2tiwSQ');
